# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-032706ca-efd3-46f6-bee0-5475f36c2a2a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-032706ca-efd3-46f6-bee0-5475f36c2a2a".device = "/dev/disk/by-uuid/032706ca-efd3-46f6-bee0-5475f36c2a2a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/47D4-84BE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3b57e8c2-496e-4cc6-8233-70e7b2165181"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
